### ISSUE TITLE
Wrong column in Sleep Deprivation

### ISSUE THREAD

**Issue by s-andrews** [StevenWingett/LifeSciencesTrainingDatasets#23]
Range.CSD.Threshold is a character vector, but the docs say it's numeric

**Comment by Casey-Brown** [comment]
This one I'm a bit unsure about because to show its a range I've added the dash so should I change the documentation to reflect that it's going to not be numeric or should I change how the data is presented and have like a min and max range column?

**Comment by s-andrews** [comment]
Either way is fine.  From a training point of view it would be quite nice to keep the dash and make it a text column so people can use this to practice how to split this apart into min and max values.
