### ISSUE TITLE
Have a way to list or query the datasets

### ISSUE THREAD

**Issue by s-andrews** [StevenWingett/LifeSciencesTrainingDatasets#4]
At the moment I couldn't see a way to list all of the datasets in the package, or get an overview for what they are.  Would be nice if there was an annotation file for the datasets which you could then add a function to see.  Eg:

```list_training_data()```

..which gives you back a data frame of all of the names descriptions, sources and other annotation.

**Comment by s-andrews** [comment]
Never mind - found the Data_Record dataset.

**Comment by Casey-Brown** [comment]
I should probably rename it to something a bit more descriptive anyway

Sent from my iPhone

On 21 Jul 2020, at 1:32 pm, Simon Andrews <notifications@github.com> wrote:

﻿

Closed #4<https://github.com/StevenWingett/LifeSciencesTrainingDatasets/issues/4>.
